export interface Institution {
  id: string;
  name: string;
  domain: string;
  city: string;
  directors: number;
  openSlots: number;
  liveVentures: number;
  reachedRevenue: number;
  points: number;
  country: "India" | "USA";
  category: "College" | "HighSchool";
}

export interface DirectorItem {
  id: string;
  name: string;
  city: string;
  subtitle: string;
  initials: string;
  role: "CAMPUS DIRECTOR" | "CITY DIRECTOR";
  turf: string;
  ventures?: string;
  revenue?: string;
  walkIns?: string;
  isOpen: boolean;
  claimText?: string;
}

export interface DirectorsDataset {
  banner: string;
  ctaText: string;
  cities?: string[];
  items: DirectorItem[];
}

export interface FoundingMember {
  id: string;
  name: string;
  location: string;
  initials: string;
  category: "Security" | "Design" | "Bug Fix" | "UX Suggestion" | "Community" | "Development";
  description: string;
  joined: string;
}

export const LEADERBOARD_INSTITUTIONS: Institution[] = [
  // India Colleges
  {
    id: "in-col-1",
    name: "Christ University",
    domain: "christuniversity.in",
    city: "Bangalore",
    directors: 2,
    openSlots: 0,
    liveVentures: 17,
    reachedRevenue: 4,
    points: 248,
    country: "India",
    category: "College",
  },
  {
    id: "in-col-2",
    name: "PES University",
    domain: "pes.edu",
    city: "Bangalore",
    directors: 1,
    openSlots: 1,
    liveVentures: 11,
    reachedRevenue: 2,
    points: 184,
    country: "India",
    category: "College",
  },
  {
    id: "in-col-3",
    name: "SRM Institute of Science and Technology",
    domain: "srmist.edu.in",
    city: "Chennai",
    directors: 2,
    openSlots: 0,
    liveVentures: 14,
    reachedRevenue: 3,
    points: 172,
    country: "India",
    category: "College",
  },
  {
    id: "in-col-4",
    name: "Symbiosis International University",
    domain: "siu.edu.in",
    city: "Pune",
    directors: 1,
    openSlots: 1,
    liveVentures: 11,
    reachedRevenue: 2,
    points: 156,
    country: "India",
    category: "College",
  },
  {
    id: "in-col-5",
    name: "IIT Bombay",
    domain: "iitb.ac.in",
    city: "Mumbai",
    directors: 2,
    openSlots: 0,
    liveVentures: 9,
    reachedRevenue: 2,
    points: 142,
    country: "India",
    category: "College",
  },
  {
    id: "in-col-6",
    name: "IIT Delhi",
    domain: "iitd.ac.in",
    city: "Delhi NCR",
    directors: 0,
    openSlots: 2,
    liveVentures: 6,
    reachedRevenue: 1,
    points: 98,
    country: "India",
    category: "College",
  },
  {
    id: "in-col-7",
    name: "BITS Pilani",
    domain: "bits-pilani.ac.in",
    city: "Hyderabad",
    directors: 1,
    openSlots: 1,
    liveVentures: 8,
    reachedRevenue: 1,
    points: 94,
    country: "India",
    category: "College",
  },
  {
    id: "in-col-8",
    name: "RV College of Engineering",
    domain: "rvce.edu.in",
    city: "Bangalore",
    directors: 2,
    openSlots: 0,
    liveVentures: 7,
    reachedRevenue: 1,
    points: 86,
    country: "India",
    category: "College",
  },
  // India High Schools
  {
    id: "in-hs-1",
    name: "Delhi Public School, R.K. Puram",
    domain: "dpsrkp.net",
    city: "New Delhi",
    directors: 1,
    openSlots: 1,
    liveVentures: 8,
    reachedRevenue: 1,
    points: 112,
    country: "India",
    category: "HighSchool",
  },
  {
    id: "in-hs-2",
    name: "The International School Bangalore (TISB)",
    domain: "tisb.org",
    city: "Bangalore",
    directors: 1,
    openSlots: 0,
    liveVentures: 6,
    reachedRevenue: 1,
    points: 94,
    country: "India",
    category: "HighSchool",
  },
  {
    id: "in-hs-3",
    name: "National Public School, Indiranagar",
    domain: "npsinr.com",
    city: "Bangalore",
    directors: 1,
    openSlots: 1,
    liveVentures: 5,
    reachedRevenue: 0,
    points: 68,
    country: "India",
    category: "HighSchool",
  },
  {
    id: "in-hs-4",
    name: "Dhirubhai Ambani International School",
    domain: "da-is.org",
    city: "Mumbai",
    directors: 0,
    openSlots: 2,
    liveVentures: 4,
    reachedRevenue: 0,
    points: 52,
    country: "India",
    category: "HighSchool",
  },
  // USA Colleges
  {
    id: "us-col-1",
    name: "Virginia Commonwealth University",
    domain: "vcu.edu",
    city: "Richmond, VA",
    directors: 1,
    openSlots: 1,
    liveVentures: 4,
    reachedRevenue: 1,
    points: 74,
    country: "USA",
    category: "College",
  },
  {
    id: "us-col-2",
    name: "University of Richmond",
    domain: "richmond.edu",
    city: "Richmond, VA",
    directors: 0,
    openSlots: 2,
    liveVentures: 2,
    reachedRevenue: 0,
    points: 38,
    country: "USA",
    category: "College",
  },
  {
    id: "us-col-3",
    name: "University of Virginia",
    domain: "virginia.edu",
    city: "Charlottesville, VA",
    directors: 0,
    openSlots: 2,
    liveVentures: 1,
    reachedRevenue: 0,
    points: 15,
    country: "USA",
    category: "College",
  },
  // USA High Schools
  {
    id: "us-hs-1",
    name: "Maggie L. Walker Governor's School",
    domain: "mlwgs.com",
    city: "Richmond, VA",
    directors: 1,
    openSlots: 1,
    liveVentures: 3,
    reachedRevenue: 0,
    points: 44,
    country: "USA",
    category: "HighSchool",
  },
  {
    id: "us-hs-2",
    name: "Deep Run High School",
    domain: "henricoschools.us",
    city: "Glen Allen, VA",
    directors: 0,
    openSlots: 2,
    liveVentures: 1,
    reachedRevenue: 0,
    points: 12,
    country: "USA",
    category: "HighSchool",
  },
];

export const DIRECTORS_DATA = {
  in: {
    campus: {
      banner: "Campus Directors run single campuses. Apply to represent your college and build the founder network on your campus.",
      ctaText: "Apply as Campus Director",
      cities: ["All", "Bangalore", "Chennai", "Pune", "Mumbai", "Delhi"],
      items: [
        {
          id: "dir-in-1",
          name: "Tanvir Ahmed",
          city: "Bangalore",
          subtitle: "Christ University, Bangalore",
          initials: "TA",
          role: "CAMPUS DIRECTOR" as const,
          turf: "Koramangala + Indiranagar · 5 active merchants",
          ventures: "17",
          revenue: "4",
          walkIns: "340",
          isOpen: false,
        },
        {
          id: "dir-in-2",
          name: "Sneha Rao",
          city: "Bangalore",
          subtitle: "PES University, Bangalore",
          initials: "SR",
          role: "CAMPUS DIRECTOR" as const,
          turf: "Jayanagar + JP Nagar · 4 active merchants",
          ventures: "11",
          revenue: "2",
          walkIns: "218",
          isOpen: false,
        },
        {
          id: "dir-in-3",
          name: "Open slot - IIT Delhi",
          city: "Delhi",
          subtitle: "Delhi NCR corridor",
          initials: "❓",
          role: "CAMPUS DIRECTOR" as const,
          turf: "This campus is waiting for its first Director. Build the founder presence at IIT Delhi.",
          claimText: "Claim this slot",
          isOpen: true,
        },
        {
          id: "dir-in-4",
          name: "Ravi Venkat",
          city: "Chennai",
          subtitle: "SRM Institute of Science & Tech",
          initials: "RV",
          role: "CAMPUS DIRECTOR" as const,
          turf: "Anna Nagar + Vadapalani · 5 active merchants",
          ventures: "14",
          revenue: "3",
          walkIns: "280",
          isOpen: false,
        },
        {
          id: "dir-in-5",
          name: "Aditya More",
          city: "Pune",
          subtitle: "Symbiosis International, Pune",
          initials: "AM",
          role: "CAMPUS DIRECTOR" as const,
          turf: "FC Road + Baner · 3 active merchants",
          ventures: "11",
          revenue: "2",
          walkIns: "176",
          isOpen: false,
        },
        {
          id: "dir-in-6",
          name: "Nisha Kulkarni",
          city: "Mumbai",
          subtitle: "IIT Bombay, Mumbai",
          initials: "NK",
          role: "CAMPUS DIRECTOR" as const,
          turf: "Powai + Andheri · 5 active merchants",
          ventures: "9",
          revenue: "2",
          walkIns: "198",
          isOpen: false,
        },
      ],
    },
    city: {
      banner: "City Directors oversee an entire metro corridor. One per city. Every campus in your territory reports through you.",
      ctaText: "Apply as City Director",
      items: [
        {
          id: "dir-city-in-1",
          name: "Karthik Dinesh",
          city: "Bangalore",
          subtitle: "Bangalore Metro · 8 campuses",
          initials: "KD",
          role: "CITY DIRECTOR" as const,
          turf: "All of Bangalore: Coordinates Christ, PES, RV College & BMS Campus Directors",
          ventures: "32",
          revenue: "7",
          walkIns: "740",
          isOpen: false,
        },
        {
          id: "dir-city-in-2",
          name: "Sowmya Natarajan",
          city: "Chennai",
          subtitle: "Chennai Metro · 5 campuses",
          initials: "SN",
          role: "CITY DIRECTOR" as const,
          turf: "All of Chennai: Coordinates SRM, VIT, and SSN Campus Directors",
          ventures: "20",
          revenue: "4",
          walkIns: "510",
          isOpen: false,
        },
        {
          id: "dir-city-in-3",
          name: "Open - Pune Metro",
          city: "Pune",
          subtitle: "Pune & Pimpri-Chinchwad",
          initials: "❓",
          role: "CITY DIRECTOR" as const,
          turf: "All of Pune: Coordinate Symbiosis, COEP, and MIT-WPU corridors.",
          claimText: "Apply for Pune",
          isOpen: true,
        },
      ],
    },
  },
  us: {
    campus: {
      banner: "US Launch — Richmond, Virginia. Seeding our first US campuses now. First to claim owns the turf in their college.",
      ctaText: "Apply as Campus Director",
      cities: ["All", "Richmond"],
      items: [
        {
          id: "dir-us-1",
          name: "Open - Richmond, VA",
          city: "Richmond",
          subtitle: "VCU / Short Pump area",
          initials: "❓",
          role: "CAMPUS DIRECTOR" as const,
          turf: "Greater Richmond metro area. Be the first Campus Director in the US.",
          claimText: "Claim Richmond",
          isOpen: true,
        },
        {
          id: "dir-us-2",
          name: "Open - Charlottesville, VA",
          city: "Charlottesville",
          subtitle: "UVA Campus corridor",
          initials: "❓",
          role: "CAMPUS DIRECTOR" as const,
          turf: "Ground-floor opportunity to lead University of Virginia founder ecosystem.",
          claimText: "Claim UVA Slot",
          isOpen: true,
        },
      ],
    },
    city: {
      banner: "US City Directors run an entire metro. Coordinate all Campus Directors across your territory.",
      ctaText: "Apply as City Director",
      items: [
        {
          id: "dir-city-us-1",
          name: "Open - New York City",
          city: "New York",
          subtitle: "NYC Metro area",
          initials: "❓",
          role: "CITY DIRECTOR" as const,
          turf: "All NYC boroughs. Coordinate Columbia, NYU, Fordham, and Baruch corridors.",
          claimText: "Apply for NYC",
          isOpen: true,
        },
      ],
    },
  },
};

export const FOUNDING_MEMBERS_DATA = {
  in: {
    stats: { members: 47, bugs: 12, vulns: 8, design: 23 },
    members: [
      {
        id: "fm-in-1",
        name: "VT Pranav Jeyan",
        location: "Koramangala, Bangalore",
        initials: "PJ",
        category: "Security" as const,
        description: "Identified a critical auth-flow vulnerability in the Spark team-formation endpoint that would have allowed uninvited users to join private groups.",
        joined: "Joined March 2026",
      },
      {
        id: "fm-in-2",
        name: "Ananga Rao",
        location: "PES University, Bengaluru",
        initials: "AR",
        category: "Design" as const,
        description: "Co-designed the Deals Near You card layout and proposed the split drive-in UI vs. delivery visual distinction that is now moving to the fill-rate mechanic section.",
        joined: "Joined January 2026",
      },
      {
        id: "fm-in-3",
        name: "Siddharth Kumar",
        location: "RVCE, Bengaluru",
        initials: "SK",
        category: "Bug Fix" as const,
        description: "Found and documented a race condition in the Spark expiry timer that caused group chats to form before the creator had accepted all members.",
        joined: "Joined January 2026",
      },
      {
        id: "fm-in-4",
        name: "Meera Pillai",
        location: "Christ University, Bangalore",
        initials: "MP",
        category: "UX Suggestion" as const,
        description: "Proposed adding the '16 of 20 Sparks filled' counter to the create screen after beta testing showed student groups were missing urgency context.",
        joined: "Joined February 2026",
      },
      {
        id: "fm-in-5",
        name: "Rohan Nair",
        location: "Indiranagar, Bangalore",
        initials: "RN",
        category: "Community" as const,
        description: "Ran the first 20 manual Sparks during closed beta, personally responding to user feedback and helping test Spark-to-merchant verification workflow.",
        joined: "Joined December 2025",
      },
      {
        id: "fm-in-6",
        name: "Vikram Sharma",
        location: "IIT Delhi, New Delhi",
        initials: "VS",
        category: "Development" as const,
        description: "Executed a static analysis of the client bundle and surfaced two hardcoded API keys that were unintentionally included in a pre-release build.",
        joined: "Joined April 2026",
      },
      {
        id: "fm-in-7",
        name: "Priya Bair",
        location: "IIT Madras, Chennai",
        initials: "PB",
        category: "Design" as const,
        description: "Co-designed the Aspiring Venture Club stage roll-up and the Showcase card layout, ensuring the high school programme felt distinct from the college tier.",
        joined: "Joined March 2026",
      },
      {
        id: "fm-in-8",
        name: "Arjun Mehta",
        location: "BITS Pilani, Hyderabad",
        initials: "AM",
        category: "Development" as const,
        description: "Built the working prototype of the Merchant Margin Calculator in SheetJS, validating the core math model before the app rewrite even began.",
        joined: "Joined March 2026",
      },
      {
        id: "fm-in-9",
        name: "Kavya Reddy",
        location: "IIT Delhi, New Delhi",
        initials: "KR",
        category: "Bug Fix" as const,
        description: "Found and reproduced a ghost-messaging bug where QR-scan group-chats were stored in local text storage, causing cross-timezone messaging lag.",
        joined: "Joined April 2026",
      },
    ],
  },
  us: {
    stats: { members: 8, bugs: 3, vulns: 2, design: 4 },
    members: [
      {
        id: "fm-us-1",
        name: "Jordan Mills",
        location: "Richmond, Virginia",
        initials: "JM",
        category: "Community" as const,
        description: "First US Campus Director candidate at VCU. Ran initial student outreach in Broad Street, identified the first 3 merchant prospects in the pilot corridor.",
        joined: "Joined May 2026",
      },
      {
        id: "fm-us-2",
        name: "Sarah Chen",
        location: "Richmond, Virginia",
        initials: "SC",
        category: "UX Suggestion" as const,
        description: "Flagged that the in-app currency display defaulted to ₹ for US users; proposed the automatic USD/INR switch based on user profile locale.",
        joined: "Joined May 2026",
      },
      {
        id: "fm-us-3",
        name: "Marcus Rodriguez",
        location: "Short Pump, Virginia",
        initials: "MR",
        category: "Development" as const,
        description: "Validated that the DoorDash 15/20/30% commission tier model could be built into the Merchant Margin Calculator using publicly available rate data.",
        joined: "Joined June 2026",
      },
    ],
  },
};
